export const products = [
    {
      "image_url": "https://hoff.ru/upload/hoff_resize/hoff-images/512/279/2/7c1dc84c38677e2df86b561a59098128.jpg/1500x1000_85.jpeg",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 123456789012,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": 1000,
      "type_of_care": ["Уход за телом"]
    },
    {
      "image_url": "https://экономь.рф/images/detailed/14/54.png",
      "name": "Средство для мытья посуды",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 234567890123,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": 49,
      "type_of_care": ["Уход за руками"]
    },
    {
      "image_url": "https://cdn1.ozone.ru/multimedia/1027168374.jpg",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 345678901234,
      "manufacturer": "Sorti",
      "brand": "Sorti",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 2000,
      "type_of_care": ["Уход за ногами"]
    },
    {
      "image_url": "https://images-eu.ssl-images-amazon.com/images/I/51GXONoJ4AL.jpg",
      "name": "Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 456789012345,
      "manufacturer": "ARIEL",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1000,
      "type_of_care": ["Уход за лицом"]
    },
    {
      "image_url": "http://sbt-volga.ru/uploads/store/product/29423.jpeg",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 567890123456,
      "manufacturer": "BIMAX",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 49,
      "type_of_care": ["Уход за волосами"]
    },
    {
      "image_url": "https://hoff.ru/upload/hoff_resize/hoff-images/512/279/2/7c1dc84c38677e2df86b561a59098128.jpg/1500x1000_85.jpeg",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 678901234567,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 750,
      "type_of_care": ["Средства для загара"]
    },
    {
      "image_url": "https://экономь.рф/images/detailed/14/54.png",
      "name": "Средство для мытья посуды",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 789012345678,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 150,
      "type_of_care": ["Средства для бритья"]
    },
    {
      "image_url": "https://cdn1.ozone.ru/multimedia/1027168374.jpg",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 8901123456789,
      "manufacturer": "Sorti",
      "brand": "Sorti",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 100,
      "type_of_care": ["Уход за телом", "Уход за руками"]
    },
    {
      "image_url": "https://images-eu.ssl-images-amazon.com/images/I/51GXONoJ4AL.jpg",
      "name": "Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 901234567890,
      "manufacturer": "ARIEL",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1000,
      "type_of_care": ["Уход за телом", "Средства для загара"]
    },
    {
      "image_url": "http://sbt-volga.ru/uploads/store/product/29423.jpeg",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 129345678901,
      "manufacturer": "BIMAX",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 600,
      "type_of_care": ["Уход за лицом", "Уход за руками"]
    },
    {
      "image_url": "https://hoff.ru/upload/hoff_resize/hoff-images/512/279/2/7c1dc84c38677e2df86b561a59098128.jpg/1500x1000_85.jpeg",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 213456789012,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1000,
      "type_of_care": ["Уход за телом", "Средства для бритья"]
    },
    {
      "image_url": "https://экономь.рф/images/detailed/14/54.png",
      "name": "Средство для мытья посуды",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 132456789012,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 10,
      "type_of_care": ["Уход за волосами", "Уход за лицом"]
    },
    {
      "image_url": "https://cdn1.ozone.ru/multimedia/1027168374.jpg",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 124356789012,
      "manufacturer": "Sorti",
      "brand": "Sorti",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 70,
      "type_of_care": ["Уход за руками", "Уход за ногами"]
    },
    {
      "image_url": "https://images-eu.ssl-images-amazon.com/images/I/51GXONoJ4AL.jpg",
      "name": "Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 123546789012,
      "manufacturer": "ARIEL",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1000,
      "type_of_care": ["Средства для бритья", "Уход за лицом"]
    },
    {
      "image_url": "http://sbt-volga.ru/uploads/store/product/29423.jpeg",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 123465789012,
      "manufacturer": "BIMAX",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1050,
      "type_of_care": ["Уход за телом", "Уход за руками"]
    },
    {
      "image_url": "https://hoff.ru/upload/hoff_resize/hoff-images/512/279/2/7c1dc84c38677e2df86b561a59098128.jpg/1500x1000_85.jpeg",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "size_type": "вес",
      "size": "1 кг",
      "barcode": 123457689012,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 300,
      "type_of_care": ["Уход за руками", "Уход за волосами"]
    },
    {
      "image_url": "https://экономь.рф/images/detailed/14/54.png",
      "name": "Средство для мытья посуды",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 123456879012,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 1900,
      "type_of_care": ["Уход за телом", "Уход за волосами"]
    },
    {
      "image_url": "https://cdn1.ozone.ru/multimedia/1027168374.jpg",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "size_type": "объём",
      "size": "450 мл",
      "barcode": 123456798012,
      "manufacturer": "Sorti",
      "brand": "Sorti",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
      "price": 100,
      "type_of_care": ["Уход за телом", "Средства для бритья"]
    }
  ]
